#!/usr/bin/env bash
# Launch a 2A2F attention/FFN multiplexing deployment for HunyuanImage-3.0 AR.
#
# The attention and FFN servers are two independent single-stage AFD peers
# (wired via the p2pconnector), so each needs its own deploy config. Rather
# than maintain four near-identical YAMLs, both configs are rendered from the
# single template below, parameterised by run mode (eager/graph) and role.
#
# Usage: ./run.sh [eager|graph]   (default: graph)
#   eager - enforce_eager, no cudagraph capture (debugging)
#   graph - FULL_DECODE_ONLY cudagraph capture (performance)
set -euo pipefail

MODE="${1:-graph}"
MODEL_PATH="${MODEL_PATH:-/path/model_weights/DeepSeek-V2-Lite}"
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
GEN_DIR="$SCRIPT_DIR/.generated/$MODE"

case "$MODE" in
  eager)
    COMPILATION='    enforce_eager: true' ;;
  graph)
    COMPILATION='    max_cudagraph_capture_size: 64
    compilation_config:
      cudagraph_mode: "FULL_DECODE_ONLY"
      cudagraph_capture_sizes: [64]' ;;
  *)
    echo "Unknown mode '$MODE' (expected 'eager' or 'graph')" >&2; exit 1 ;;
esac

# Render one single-stage AFD deploy config. Args: role worker devices port
render() {
  local role="$1" worker="$2" devices="$3" port="$4"
  cat <<EOF
# Generated by run.sh ($MODE / $role) — do not edit; change the template in run.sh.
pipeline: hunyuan_image3_ar
async_chunk: false

stages:
  - stage_id: 0
    worker_cls: "$worker"
    data_parallel_size: 1
    tensor_parallel_size: 2
    enable_expert_parallel: true
    max_num_seqs: 64
    gpu_memory_utilization: 0.75
    trust_remote_code: true
$COMPILATION
    enable_prefix_caching: false
    max_num_batched_tokens: 8192
    devices: "$devices"
    port: $port
    host: 127.0.0.1
    enable_dbo: true
    dbo_decode_token_threshold: 2
    dbo_prefill_token_threshold: 12

    hf_overrides:
      rope_parameters:
        mrope_section: [0, 32, 32]
        rope_type: default
    default_sampling_params:
      temperature: 0.0
      top_p: 0.95
      top_k: 1024
      max_tokens: 1024
      detokenize: true

    additional_config:
      afd:
        enabled: true
        role: "$role"
        connector: "p2pconnector"
        num_attention_servers: 2
        num_ffn_servers: 2
        extra_config:
          afd_size: "2A2F"
EOF
}

mkdir -p "$GEN_DIR"
render attention afd_plugin.v1.worker.AFDAttentionWorker "0,1" 18300 > "$GEN_DIR/attn.yaml"
render ffn       afd_plugin.v1.worker.AFDFFNWorker       "2,3" 18301 > "$GEN_DIR/ffn.yaml"

CUDA_VISIBLE_DEVICES=0,1 uv run vllm serve "$MODEL_PATH" \
    --host 127.0.0.1 \
    --port 18300 \
    --omni \
    --deploy-config "$GEN_DIR/attn.yaml" > attn.log 2>&1 &

CUDA_VISIBLE_DEVICES=2,3 uv run vllm serve "$MODEL_PATH" \
    --host 127.0.0.1 \
    --port 18301 \
    --omni \
    --deploy-config "$GEN_DIR/ffn.yaml" > ffn.log 2>&1 &

wait
